- name: Install dependencies
  apt:
    name: acl
    state: present

- name: Create Hadoop Group
  group:
    name: hadoop
    state: present

- name: Check if Hadoop directory exists
  ansible.builtin.stat:
    path: /opt/hadoop
  register: hadoop_dir

- name: Check if Hadoop archive exists on control node
  ansible.builtin.stat:
    path: "/tmp/{{ hadoop_archive }}"
  register: hadoop_archive_file
  delegate_to: localhost
  run_once: true
  become: false

- name: Download Hadoop archive file to control node
  get_url:
    url: "{{ hadoop_url }}"
    dest: "/tmp/{{ hadoop_archive }}"
    timeout: 300
  when: not hadoop_archive_file.stat.exists
  delegate_to: localhost
  run_once: true
  become: false

- name: Copy Hadoop archive file to remote nodes
  copy:
    src: "/tmp/{{ hadoop_archive }}"
    dest: "/tmp/{{ hadoop_archive }}"
  when: not hadoop_dir.stat.exists

- name: Unarchive the file
  ansible.builtin.unarchive:
    src: "/tmp/{{ hadoop_archive }}"
    dest: "/opt"
    creates: "/opt/{{ hadoop_archive | replace('.tar.gz', '') }}"
    remote_src: yes
    group: hadoop
  when: not hadoop_dir.stat.exists

- name: Create a symbolic link
  file:
    src: "/opt/{{ hadoop_archive | replace('.tar.gz', '') }}"
    dest: "/opt/hadoop"
    state: "link"
  when: not hadoop_dir.stat.exists

- name: Remove unarchive file
  file:
    path: /tmp/{{ hadoop_archive }}
    state: absent
  when: not hadoop_dir.stat.exists

- name: Create a necessary directories
  file:
    path: "/opt/hadoop/{{ item }}"
    group: hadoop
    mode: "0775"
    state: "directory"
  loop:
    - logs
    - tmp

- name: Copy setting files to hadoop dir
  template:
    src: "{{ item }}.j2"
    dest: "/opt/hadoop/etc/hadoop/{{ item }}"
    group: hadoop
    mode: "0644"
  loop:
    - hadoop-env.sh
    - core-site.xml
    - workers

- name: Create a Hadoop security dir
  file:
    path: "{{ item }}"
    state: "directory"
  loop:
    - /etc/ssl/hadoop
    - /etc/security/keytab

- name: Copy SSL credentials
  copy:
    src: "jks/{{ item }}"
    dest: /etc/ssl/hadoop
    group: hadoop
    mode: "0644"
  loop:
    - "keystore.jks"
    - "truststore.jks"

- name: Copy setting files to hadoop dir
  template:
    src: "{{ item }}.j2"
    dest: "/opt/hadoop/etc/hadoop/{{ item }}"
    group: hadoop
    mode: "0644"
  loop:
    - ssl-server.xml

- name: Add /opt/hadoop/bin to global PATH in /etc/profile.d
  ansible.builtin.file:
    path: /etc/profile.d/hadoop.sh
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Ensure /opt/hadoop/bin is in PATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/hadoop.sh
    line: 'export PATH=/opt/hadoop/bin:$PATH'
    state: present
    create: yes
