- name: Create MapReduce user
  user:
    name: mapred
    group: hadoop
    state: present
    shell: /bin/bash

- name: Copy keytab files
  copy:
    src: keytab/jhs.service.keytab
    dest: /etc/security/keytab/jhs.service.keytab
    owner: mapred
    group: hadoop
    mode: "0600"

- name: Copy setting files to hadoop dir
  template:
    src: mapred-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/mapred-site.xml
    group: hadoop
    mode: "0644"
    directory_mode: "0755"

- name: Copy systemd service file
  copy:
    src: "systemd/hadoop-{{ item }}.service"
    dest: "/etc/systemd/system/hadoop-{{ item }}.service"
    owner: root
    group: root
    mode: "0644"
  loop:
    - historyserver
