- name: Create Yarn user
  user:
    name: yarn
    group: hadoop
    state: present
    shell: /bin/bash

- name: Copy keytab files
  copy:
    src: "keytab/{{ item }}"
    dest: "/etc/security/keytab/{{ item }}"
    owner: yarn
    group: hadoop
    mode: "0600"
  loop:
    - "rm.service.keytab"
    - "nm.service.keytab"

- name: Copy setting files to hadoop dir
  template:
    src: "{{ item }}.j2"
    dest: "/opt/hadoop/etc/hadoop/{{ item }}"
    group: hadoop
    mode: "0644"
    directory_mode: "0755"
  loop:
    - yarn-site.xml
    - container-executor.cfg

- name: Change permission of container-executor binary
  file:
    path: /opt/hadoop/bin/container-executor
    mode: "4750"

# Downgrade OpenSSL to 1.1.1 for Linux Container Executor
# (Default in many case is more than 3.0)

- name: Check currently installed OpenSSL version
  command: openssl version
  register: openssl_version_output
  failed_when: false
  changed_when: false

- name: Downgrade OpenSSL to 1.1
  when: "'OpenSSL 1.1' not in openssl_version_output.stdout" 
  block:
  - name: Install dependencies for OpenSSL build
    apt:
      name:
        - build-essential
        - checkinstall
        - zlib1g-dev
      state: present

  - name: Check if OpenSSL 1.1.1 archive already exists
    stat:
      path: /tmp/openssl-1.1.1.tar.gz
    register: openssl_archive_exists
    delegate_to: localhost
    become: false

  - name: Download OpenSSL 1.1.1 archive file to control node
    get_url:
      url: https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1/openssl-1.1.1.tar.gz
      dest: /tmp
      timeout: 300
    delegate_to: localhost
    become: false
    when: not openssl_archive_exists.stat.exists

  - name: Copy OpenSSL 1.1.1 archive file to remote nodes
    copy:
      src: /tmp/openssl-1.1.1.tar.gz
      dest: /tmp/openssl-1.1.1.tar.gz

  - name: Unarchive the file
    ansible.builtin.unarchive:
      src: /tmp/openssl-1.1.1.tar.gz
      dest: /tmp
      remote_src: yes

  - name: Remove archive file
    file:
      path: /tmp/openssl-1.1.1.tar.gz
      state: absent

  - name: Build and install OpenSSL 1.1
    shell: |
      ./config
      make
      make install
    args:
      chdir: /tmp/openssl-1.1.1

  - name: Reload shared library cache
    command: ldconfig

  - name: Set OpenSSL 1.1.1 as the default
    alternatives:
      name: openssl
      link: /usr/bin/openssl
      path: /usr/local/bin/openssl
      priority: 100

  - name: Remove source directory
    file:
      path: /tmp/openssl-1.1.1
      state: absent
