- name: Install requirements
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - sssd
    - sssd-krb5
    - sssd-ldap
    - sssd-tools
    - libnss-sss
    - libpam-sss

- name: Copy sssd.conf
  copy:
    src: sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600

- name: auth update
  command: pam-auth-update --package

- name: Start sssd
  command: service sssd restart
