- name: Install Kerberos client
  apt:
    name: "krb5-user"
    state: present

- name: Set krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
