libdefaults:
  default_realm: HOME
  dns_lookup_kdc: true
  dns_lookup_realm: false
  ticket_lifetime: 24h
  renew_lifetime: 7d
  forwardable: true
  proxiable: true
  rdns: true

realms:
  HOME:
    kdc: kdc.home
    admin_server: kdc.home

domain_realm:
  .home: HOME
  home: HOME
