airflow_venv: /opt/airflow/venv
airflow_version: 2.10.4
python_version: 3.12
constraint_url: "https://raw.githubusercontent.com/apache/airflow/constraints-{{ airflow_version }}/constraints-{{ python_version }}.txt"
hive_extension_version: 8.1.2
