# Download and install JDK 8 for Hadoop
# Set this JAVA_HOME later in Hadoop enviroment config file (hadoop-env.sh)

- name: Check if JDK archive exists on control node
  ansible.builtin.stat:
    path: "/tmp/{{ jdk_archive }}"
  register: jdk_archive_file
  delegate_to: localhost

- name: Download JDK archive file
  get_url:
    url: "{{ jdk_url }}"
    dest: "/tmp/{{ jdk_archive }}"
    timeout: 300
  when: not jdk_archive_file.stat.exists
  delegate_to: localhost
  run_once: true

- name: Copy JDK archive file to remote nodes
  copy:
    src: "/tmp/{{ jdk_archive }}"
    dest: "/tmp/{{ jdk_archive }}"

- name: Unarchive the file
  ansible.builtin.unarchive:
    src: "/tmp/{{ jdk_archive }}"
    dest: "/opt/"
    creates: "/opt/{{ jdk_archive | replace('.tar.gz', '') }}"
    remote_src: yes

- name: Link to /opt/java
  file:
    src: "/opt/{{ jdk_archive | replace('.tar.gz', '') }}"
    dest: "/opt/java"
    state: link

- name: Set JAVA_HOME fact
  set_fact:
    java_home: "/opt/{{ jdk_archive | replace('.tar.gz', '') }}"

- name: Rmove unarchive file
  file:
    path: "/tmp/{{ jdk_archive }}"
    state: absent
