- name: Check if Spark directory exists
  ansible.builtin.stat:
    path: /opt/spark
  register: spark_dir

- name: Check if Spark archive exists on control node
  ansible.builtin.stat:
    path: "/tmp/{{ spark_archive }}"
  register: spark_archive_file
  delegate_to: localhost

- name: Download Spark archive file to control node
  get_url:
    url: "{{ spark_url }}"
    dest: "/tmp/{{ spark_archive }}"
    timeout: 300
  when: not spark_dir.stat.exists and not spark_archive_file.stat.exists
  delegate_to: localhost
  run_once: true

- name: Copy Spark archive file to remote nodes
  copy:
    src: "/tmp/{{ spark_archive }}"
    dest: "/tmp/{{ spark_archive }}"
  when: not spark_dir.stat.exists

- name: Unarchive the file
  ansible.builtin.unarchive:
    src: "/tmp/{{ spark_archive }}"
    dest: "/opt"
    creates: "/opt/{{ spark_archive | replace('.tgz', '') }}"
    remote_src: yes
  when: not spark_dir.stat.exists

- name: Create a symbolic link
  file:
    src: "/opt/{{ spark_archive | replace('.tgz', '') }}"
    dest: "/opt/spark"
    state: "link"
  when: not spark_dir.stat.exists

- name: Remove unarchive file
  file:
    path: /tmp/{{ spark_archive }}
    state: absent
  when: not spark_dir.stat.exists

- name: Copy setting files to spark conf dir
  template:
    src: "{{ item }}.j2"
    dest: "/opt/spark/conf/{{ item }}"
  loop:
    - spark-env.sh
    - spark-defaults.conf

- name: Add /opt/spark/bin to global PATH in /etc/profile.d
  ansible.builtin.file:
    path: /etc/profile.d/spark.sh
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Ensure /opt/spark/bin is in PATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/spark.sh
    line: 'export PATH=/opt/spark/bin:$PATH'
    state: present
    create: yes
