- name: Install venv package
  apt:
    name:
      - python3-venv
    state: present

- name: Create a virtual environment
  command: python3 -m venv "{{ airflow_venv }}"
  args:
    creates: "{{ airflow_venv }}"

- name: Install Airflow with pip
  command: "{{ airflow_venv }}/bin/pip install \"apache-airflow=={{ airflow_version }}\" --constraint {{ constraint_url }}"

- name: Create Airflow directory
  file:
    path: "{{ ansible_env.HOME }}/airflow"
    state: directory

- name: Copy the airflow.cfg file
  copy:
    src: airflow.cfg
    dest: "{{ ansible_env.HOME }}/airflow/airflow.cfg"

- name: Create keytab directory
  file:
    path: /etc/security/airflow
    state: directory

- name: Set a keytab file
  copy:
    src: airflow.keytab
    dest: /etc/security/airflow/airflow.keytab

- name: Install Kerberos
  apt:
    name: krb5-user
    state: present

- name: Add Realm to Kerberos
  lineinfile:
    path: /etc/krb5.conf
    insertafter: "^\\[realms\\]"
    line: |
      HOME = {
        kdc = kdc.home
        admin_server = kdc.home
      }

- name: Change default_realm
  ansible.builtin.lineinfile:
    path: /etc/krb5.conf
    regexp: "^(\\s*)default_realm\\s*="
    line: "\\1default_realm = HOME"
    backrefs: yes

- name: Start standalone server
  shell: |
    . "{{ airflow_venv }}"/bin/activate
    airflow db migrate > /tmp/airflow_db_migrate.log 2>&1
    airflow standalone > /tmp/airflow_standalone.log 2>&1 &
    airflow kerberos > /tmp/airflow_kerberos.log 2>&1 &
