- name: Install venv package
  apt:
    name:
      - python3-venv
      - libsasl2-dev
      - libldap2-dev
      - libssl-dev
    state: present

- name: Create a virtual environment
  command: python3 -m venv "{{ airflow_venv }}"
  args:
    creates: "{{ airflow_venv }}"

- name: Install Airflow with pip
  command: "{{ airflow_venv }}/bin/pip install \"apache-airflow[ldap]=={{ airflow_version }}\" --constraint {{ constraint_url }}"

- name: Create Airflow directory
  file:
    path: "{{ ansible_env.HOME }}/airflow"
    state: directory

- name: Copy the airflow.cfg file
  template:
    src: "{{ item }}.j2" 
    dest: "{{ ansible_env.HOME }}/airflow/{{ item }}"
  loop:
    - airflow.cfg
    - webserver_config.py

- name: Create keytab directory
  file:
    path: /etc/security/airflow
    state: directory

- name: Set a keytab file
  copy:
    src: airflow.keytab
    dest: /etc/security/airflow/airflow.keytab

- name: Start standalone server
  shell: |
    . "{{ airflow_venv }}"/bin/activate
    airflow db migrate > /tmp/airflow_db_migrate.log 2>&1
    airflow standalone > /tmp/airflow_standalone.log 2>&1 &
    airflow kerberos > /tmp/airflow_kerberos.log 2>&1 &
