- name: Install Hadoop cluster
  hosts:
    - hadoop_namenode
    - hadoop_datanode
  become: true
  roles:
    - krb
    - java
    - hadoop
    - spark

- name: Install Hive
  hosts: hadoop_namenode
  become: true
  roles:
    - hive

- name: Install Airflow
  hosts: airflow
  become: true
  roles:
    - krb
    - airflow

- name: Install JupyterHub
  hosts: jupyterhub
  become: true
  roles:
    - krb
    - jupyterhub
